# -*- coding: utf-8 -*-
"""1_or_gate.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yfj6yQVIak2aeDMkVCetrfKuWemK-e0b
"""

pip install qiskit

pip install qiskit-aer



from qiskit import QuantumCircuit
qc = QuantumCircuit(3,3)

qc.h([0,1])

qc.measure(0,0)
with qc.if_test((0,1)):
  qc.x(2)
  qc.measure(2,2)

qc.measure(1,1)
with qc.if_test((1,1)):
  with qc.if_test((2,0)):
    qc.x(2)

qc.measure(2,2)
qc.draw()